name: hawk_fab_menu
description: A floating action button menu that will pop up small fabs on top
version: 0.3.2
homepage: https://github.com/arnold-parge/hawk_fab_menu

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
